#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook 'mongodb',
    :github => 'edelight/chef-mongodb'

cookbook 'php-fpm',
    :github => 'yevgenko/cookbook-php-fpm'

cookbook 'teamcity',
    :github => 'mswart/chef-teamcity'

cookbook 'teamcity_server',
    :github => 'rithis-chef/cookbook-teamcity-server'

cookbook 'postgresql',
    :github => 'phlipper/chef-postgresql'

cookbook 'android-sdk',
    :github => "gildegoma/chef-android-sdk"

cookbook 'php'
cookbook 'composer'
cookbook 'nginx'
cookbook 'cron'
cookbook 'beanstalkd'
cookbook 'java'
cookbook 'iptables-ng'
cookbook 'openssh'
cookbook 'ruby'
cookbook 'ssh-util'
cookbook 'nodejs'
cookbook 'gradle'
cookbook 'composer'
cookbook 'newrelic'


