# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "default" do |hosts|
    hosts.vm.box = "precise64"
    hosts.vm.network :private_network, ip: "192.168.33.17"

    hosts.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024"]
    end

    HOSTS_VAGRANT_JSON = JSON.parse(Pathname(__FILE__).dirname.join('nodes', 'lighthouse.json').read)

    hosts.vm.provision :chef_solo do |chef|
      chef.cookbooks_path = ["site-cookbooks", "cookbooks"]
      chef.roles_path = "roles"
      chef.data_bags_path = "data_bags"
      chef.provisioning_path = "/tmp/vagrant-chef"

      chef.run_list = HOSTS_VAGRANT_JSON.delete('run_list')
      chef.json = HOSTS_VAGRANT_JSON
    end
  end

  config.vm.define "tests" do |tests|
    tests.vm.box = "precise64"
    tests.vm.network :private_network, ip: "192.168.33.18"

    tests.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024"]
    end

    TESTS_VAGRANT_JSON = JSON.parse(Pathname(__FILE__).dirname.join('nodes', 'tests.json').read)

    tests.vm.provision :chef_solo do |chef|
      chef.cookbooks_path = ["site-cookbooks", "cookbooks"]
      chef.roles_path = "roles"
      chef.data_bags_path = "data_bags"
      chef.provisioning_path = "/tmp/vagrant-chef"

      chef.run_list = TESTS_VAGRANT_JSON.delete('run_list')
      chef.json = TESTS_VAGRANT_JSON
    end
  end
end
