load 'deploy' if respond_to?(:namespace)

# add local recipes to load path
$:.unshift(File.expand_path('../deploy/plugins'))

require 'capifony_symfony2'

load '../deploy/recipes/deploy'
load '../deploy/recipes/log'
load '../deploy/recipes/symfony'
load '../deploy/recipes/worker'
load 'app/deploy/deploy'