load 'deploy' if respond_to?(:namespace)

# add local recipes to load path
$:.unshift(File.expand_path('../deploy/capistrano/plugins'))

require 'capifony_symfony2'

load '../deploy/capistrano/recipes/deploy'
load '../deploy/capistrano/recipes/log'
load '../deploy/capistrano/recipes/symfony'
load 'app/config/deploy'