void function( path ){                               
    var fs= require( 'fs' )                          
    var source= fs.readFileSync( path )              
    source= 'with(this){' + source + '}'             
    module._compile( source, path )                  
    return arguments.callee                          
}                                                    
    
("C:/OpenServer/domains/mayak/webfront/jin/factory/jin_factory.jam.js")
("C:/OpenServer/domains/mayak/webfront/jin/method/jin_method.jam.js")
("C:/OpenServer/domains/mayak/webfront/jin/class/jin_class.jam.js")
("C:/OpenServer/domains/mayak/webfront/jin/mixin/jin_mixin.jam.js")
("C:/OpenServer/domains/mayak/webfront/jin/registry/jin_registry.jam.js")
("C:/OpenServer/domains/mayak/webfront/jin/wrapper/jin_wrapper.jam.js")
("C:/OpenServer/domains/mayak/webfront/jin/proxy/jin_proxy.jam.js")
("C:/OpenServer/domains/mayak/webfront/jin/lazyProxy/jin_lazyProxy.jam.js")
("C:/OpenServer/domains/mayak/webfront/jin/async2sync/jin_async2sync.env=node.jam.js")
("C:/OpenServer/domains/mayak/webfront/jin/confirm/jin_confirm.env=node.jam.js")
("C:/OpenServer/domains/mayak/webfront/jin/autoloader/jin_autoloader.env=node.jam.js")
("C:/OpenServer/domains/mayak/webfront/node/node/node.env=node.jam.js")
("C:/OpenServer/domains/mayak/webfront/jin/uri/jin_uri.env=node.jam.js")
("C:/OpenServer/domains/mayak/webfront/jin/file/jin_file.env=node.jam.js")
("C:/OpenServer/domains/mayak/webfront/jin/path/jin_path.jam.js")
("C:/OpenServer/domains/mayak/webfront/jin/tree/jin_tree.jam.js")
("C:/OpenServer/domains/mayak/webfront/jin/src/jin_src.env=node.jam.js")
("C:/OpenServer/domains/mayak/webfront/jin/mod/jin_mod.env=node.jam.js")
("C:/OpenServer/domains/mayak/webfront/jin/request/jin_request.env=node.jam.js")
("C:/OpenServer/domains/mayak/webfront/jin/execute/jin_execute.env=node.jam.js")
("C:/OpenServer/domains/mayak/webfront/jin/vary2string/jin_vary2string.jam.js")
("C:/OpenServer/domains/mayak/webfront/jin/pack/jin_pack.env=node.jam.js")
("C:/OpenServer/domains/mayak/webfront/jin/pms/jin_pms.env=node.jam.js")
("C:/OpenServer/domains/mayak/webfront/jin/build4node/jin_build4node_dev.env=node.jam.js")
("C:/OpenServer/domains/mayak/webfront/jin/build4node/jin_build4node_release.env=node.jam.js")
("C:/OpenServer/domains/mayak/webfront/jin/build4web/jin_build4web_all.env=node.js")
("C:/OpenServer/domains/mayak/webfront/jin/build4web/jin_build4web_css_dev.env=node.jam.js")
("C:/OpenServer/domains/mayak/webfront/jin/build4web/jin_build4web_css_release.env=node.jam.js")
("C:/OpenServer/domains/mayak/webfront/jin/build4web/jin_build4web_doc_dev.env=node.jam.js")
("C:/OpenServer/domains/mayak/webfront/jin/build4web/jin_build4web_doc_release.env=node.jam.js")
("C:/OpenServer/domains/mayak/webfront/jin/build4web/jin_build4web_js_dev.env=node.jam.js")
("C:/OpenServer/domains/mayak/webfront/jin/build4web/jin_build4web_js_release.env=node.jam.js")
("C:/OpenServer/domains/mayak/webfront/jin/build4web/jin_build4web_xsl_dev.env=node.jam.js")
("C:/OpenServer/domains/mayak/webfront/jin/build4web/jin_build4web_xsl_release.env=node.jam.js")
("C:/OpenServer/domains/mayak/webfront/jin/sync2async/jin_sync2async.env=node.jam.js")
("C:/OpenServer/domains/mayak/webfront/jin/application/jin_application.env=node.jam.js")
("C:/OpenServer/domains/mayak/webfront/jin/throttle/jin_throttle.jam.js")
("C:/OpenServer/domains/mayak/webfront/jin/sourceWatcher/jin_sourceWatcher.env=node.jam.js")
("C:/OpenServer/domains/mayak/webfront/jin/persistent/jin_persistent.env=node.jam.js")