
package project.lighthouse.autotests.robotClient;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-09-09T11:39:32.052+04:00
 * Generated source version: 2.7.6
 */

@WebFault(name = "InterruptedException", targetNamespace = "http://ws.hub.setrobot.crystals.ru/")
public class InterruptedException_Exception extends Exception {

    private InterruptedException interruptedException;

    public InterruptedException_Exception() {
        super();
    }

    public InterruptedException_Exception(String message) {
        super(message);
    }

    public InterruptedException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public InterruptedException_Exception(String message, InterruptedException interruptedException) {
        super(message);
        this.interruptedException = interruptedException;
    }

    public InterruptedException_Exception(String message, InterruptedException interruptedException, Throwable cause) {
        super(message, cause);
        this.interruptedException = interruptedException;
    }

    public InterruptedException getFaultInfo() {
        return this.interruptedException;
    }
}
