package project.lighthouse.autotests.robotClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-09-09T11:39:32.061+04:00
 * Generated source version: 2.7.6
 */
@WebService(targetNamespace = "http://ws.hub.setrobot.crystals.ru/", name = "SetRobotHubWS")
@XmlSeeAlso({ObjectFactory.class})
public interface SetRobotHubWS {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.hub.setrobot.crystals.ru/SetRobotHubWS/runTestListRequest", output = "http://ws.hub.setrobot.crystals.ru/SetRobotHubWS/runTestListResponse", fault = {@FaultAction(className = InterruptedException_Exception.class, value = "http://ws.hub.setrobot.crystals.ru/SetRobotHubWS/runTestList/Fault/InterruptedException")})
    @RequestWrapper(localName = "runTestList", targetNamespace = "http://ws.hub.setrobot.crystals.ru/", className = "project.lighthouse.autotests.robotClient.RunTestList")
    @WebMethod
    @ResponseWrapper(localName = "runTestListResponse", targetNamespace = "http://ws.hub.setrobot.crystals.ru/", className = "project.lighthouse.autotests.robotClient.RunTestListResponse")
    public String runTestList(
            @WebParam(name = "cashIp", targetNamespace = "")
            String cashIp,
            @WebParam(name = "testList", targetNamespace = "")
            String testList
    ) throws InterruptedException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.hub.setrobot.crystals.ru/SetRobotHubWS/getTestNameRequest", output = "http://ws.hub.setrobot.crystals.ru/SetRobotHubWS/getTestNameResponse")
    @RequestWrapper(localName = "getTestName", targetNamespace = "http://ws.hub.setrobot.crystals.ru/", className = "project.lighthouse.autotests.robotClient.GetTestName")
    @WebMethod
    @ResponseWrapper(localName = "getTestNameResponse", targetNamespace = "http://ws.hub.setrobot.crystals.ru/", className = "project.lighthouse.autotests.robotClient.GetTestNameResponse")
    public String getTestName(
            @WebParam(name = "testName", targetNamespace = "")
            String testName
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.hub.setrobot.crystals.ru/SetRobotHubWS/statusRequest", output = "http://ws.hub.setrobot.crystals.ru/SetRobotHubWS/statusResponse")
    @RequestWrapper(localName = "status", targetNamespace = "http://ws.hub.setrobot.crystals.ru/", className = "project.lighthouse.autotests.robotClient.Status")
    @WebMethod
    @ResponseWrapper(localName = "statusResponse", targetNamespace = "http://ws.hub.setrobot.crystals.ru/", className = "project.lighthouse.autotests.robotClient.StatusResponse")
    public String status(
            @WebParam(name = "uuid", targetNamespace = "")
            String uuid
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.hub.setrobot.crystals.ru/SetRobotHubWS/runTestRequest", output = "http://ws.hub.setrobot.crystals.ru/SetRobotHubWS/runTestResponse", fault = {@FaultAction(className = InterruptedException_Exception.class, value = "http://ws.hub.setrobot.crystals.ru/SetRobotHubWS/runTest/Fault/InterruptedException")})
    @RequestWrapper(localName = "runTest", targetNamespace = "http://ws.hub.setrobot.crystals.ru/", className = "project.lighthouse.autotests.robotClient.RunTest")
    @WebMethod
    @ResponseWrapper(localName = "runTestResponse", targetNamespace = "http://ws.hub.setrobot.crystals.ru/", className = "project.lighthouse.autotests.robotClient.RunTestResponse")
    public String runTest(
            @WebParam(name = "cashIp", targetNamespace = "")
            String cashIp,
            @WebParam(name = "testName", targetNamespace = "")
            String testName
    ) throws InterruptedException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.hub.setrobot.crystals.ru/SetRobotHubWS/setupRequest", output = "http://ws.hub.setrobot.crystals.ru/SetRobotHubWS/setupResponse", fault = {@FaultAction(className = InterruptedException_Exception.class, value = "http://ws.hub.setrobot.crystals.ru/SetRobotHubWS/setup/Fault/InterruptedException")})
    @RequestWrapper(localName = "setup", targetNamespace = "http://ws.hub.setrobot.crystals.ru/", className = "project.lighthouse.autotests.robotClient.Setup")
    @WebMethod
    @ResponseWrapper(localName = "setupResponse", targetNamespace = "http://ws.hub.setrobot.crystals.ru/", className = "project.lighthouse.autotests.robotClient.SetupResponse")
    public String setup(
            @WebParam(name = "cashIp", targetNamespace = "")
            String cashIp,
            @WebParam(name = "shopNumber", targetNamespace = "")
            String shopNumber,
            @WebParam(name = "cashNumber", targetNamespace = "")
            String cashNumber
    ) throws InterruptedException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.hub.setrobot.crystals.ru/SetRobotHubWS/stopExecutionRequest", output = "http://ws.hub.setrobot.crystals.ru/SetRobotHubWS/stopExecutionResponse", fault = {@FaultAction(className = InterruptedException_Exception.class, value = "http://ws.hub.setrobot.crystals.ru/SetRobotHubWS/stopExecution/Fault/InterruptedException")})
    @RequestWrapper(localName = "stopExecution", targetNamespace = "http://ws.hub.setrobot.crystals.ru/", className = "project.lighthouse.autotests.robotClient.StopExecution")
    @WebMethod
    @ResponseWrapper(localName = "stopExecutionResponse", targetNamespace = "http://ws.hub.setrobot.crystals.ru/", className = "project.lighthouse.autotests.robotClient.StopExecutionResponse")
    public String stopExecution(
            @WebParam(name = "cashIp", targetNamespace = "")
            String cashIp
    ) throws InterruptedException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.hub.setrobot.crystals.ru/SetRobotHubWS/getTestListRequest", output = "http://ws.hub.setrobot.crystals.ru/SetRobotHubWS/getTestListResponse")
    @RequestWrapper(localName = "getTestList", targetNamespace = "http://ws.hub.setrobot.crystals.ru/", className = "project.lighthouse.autotests.robotClient.GetTestList")
    @WebMethod
    @ResponseWrapper(localName = "getTestListResponse", targetNamespace = "http://ws.hub.setrobot.crystals.ru/", className = "project.lighthouse.autotests.robotClient.GetTestListResponse")
    public java.util.List<String> getTestList(
            @WebParam(name = "testTags", targetNamespace = "")
            String testTags
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.hub.setrobot.crystals.ru/SetRobotHubWS/restartSystemRequest", output = "http://ws.hub.setrobot.crystals.ru/SetRobotHubWS/restartSystemResponse", fault = {@FaultAction(className = InterruptedException_Exception.class, value = "http://ws.hub.setrobot.crystals.ru/SetRobotHubWS/restartSystem/Fault/InterruptedException")})
    @RequestWrapper(localName = "restartSystem", targetNamespace = "http://ws.hub.setrobot.crystals.ru/", className = "project.lighthouse.autotests.robotClient.RestartSystem")
    @WebMethod
    @ResponseWrapper(localName = "restartSystemResponse", targetNamespace = "http://ws.hub.setrobot.crystals.ru/", className = "project.lighthouse.autotests.robotClient.RestartSystemResponse")
    public String restartSystem(
            @WebParam(name = "cashIp", targetNamespace = "")
            String cashIp
    ) throws InterruptedException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.hub.setrobot.crystals.ru/SetRobotHubWS/setupAllRequest", output = "http://ws.hub.setrobot.crystals.ru/SetRobotHubWS/setupAllResponse", fault = {@FaultAction(className = InterruptedException_Exception.class, value = "http://ws.hub.setrobot.crystals.ru/SetRobotHubWS/setupAll/Fault/InterruptedException")})
    @RequestWrapper(localName = "setupAll", targetNamespace = "http://ws.hub.setrobot.crystals.ru/", className = "project.lighthouse.autotests.robotClient.SetupAll")
    @WebMethod
    @ResponseWrapper(localName = "setupAllResponse", targetNamespace = "http://ws.hub.setrobot.crystals.ru/", className = "project.lighthouse.autotests.robotClient.SetupAllResponse")
    public String setupAll(
            @WebParam(name = "cashList", targetNamespace = "")
            String cashList
    ) throws InterruptedException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.hub.setrobot.crystals.ru/SetRobotHubWS/restartCashRequest", output = "http://ws.hub.setrobot.crystals.ru/SetRobotHubWS/restartCashResponse", fault = {@FaultAction(className = InterruptedException_Exception.class, value = "http://ws.hub.setrobot.crystals.ru/SetRobotHubWS/restartCash/Fault/InterruptedException")})
    @RequestWrapper(localName = "restartCash", targetNamespace = "http://ws.hub.setrobot.crystals.ru/", className = "project.lighthouse.autotests.robotClient.RestartCash")
    @WebMethod
    @ResponseWrapper(localName = "restartCashResponse", targetNamespace = "http://ws.hub.setrobot.crystals.ru/", className = "project.lighthouse.autotests.robotClient.RestartCashResponse")
    public String restartCash(
            @WebParam(name = "cashIp", targetNamespace = "")
            String cashIp
    ) throws InterruptedException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.hub.setrobot.crystals.ru/SetRobotHubWS/stopAllRequest", output = "http://ws.hub.setrobot.crystals.ru/SetRobotHubWS/stopAllResponse", fault = {@FaultAction(className = InterruptedException_Exception.class, value = "http://ws.hub.setrobot.crystals.ru/SetRobotHubWS/stopAll/Fault/InterruptedException")})
    @RequestWrapper(localName = "stopAll", targetNamespace = "http://ws.hub.setrobot.crystals.ru/", className = "project.lighthouse.autotests.robotClient.StopAll")
    @WebMethod
    @ResponseWrapper(localName = "stopAllResponse", targetNamespace = "http://ws.hub.setrobot.crystals.ru/", className = "project.lighthouse.autotests.robotClient.StopAllResponse")
    public String stopAll(
            @WebParam(name = "cashIp", targetNamespace = "")
            String cashIp
    ) throws InterruptedException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.hub.setrobot.crystals.ru/SetRobotHubWS/pingRequest", output = "http://ws.hub.setrobot.crystals.ru/SetRobotHubWS/pingResponse", fault = {@FaultAction(className = InterruptedException_Exception.class, value = "http://ws.hub.setrobot.crystals.ru/SetRobotHubWS/ping/Fault/InterruptedException")})
    @RequestWrapper(localName = "ping", targetNamespace = "http://ws.hub.setrobot.crystals.ru/", className = "project.lighthouse.autotests.robotClient.Ping")
    @WebMethod
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "http://ws.hub.setrobot.crystals.ru/", className = "project.lighthouse.autotests.robotClient.PingResponse")
    public String ping(
            @WebParam(name = "cashIp", targetNamespace = "")
            String cashIp
    ) throws InterruptedException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.hub.setrobot.crystals.ru/SetRobotHubWS/setupRobotRequest", output = "http://ws.hub.setrobot.crystals.ru/SetRobotHubWS/setupRobotResponse", fault = {@FaultAction(className = InterruptedException_Exception.class, value = "http://ws.hub.setrobot.crystals.ru/SetRobotHubWS/setupRobot/Fault/InterruptedException")})
    @RequestWrapper(localName = "setupRobot", targetNamespace = "http://ws.hub.setrobot.crystals.ru/", className = "project.lighthouse.autotests.robotClient.SetupRobot")
    @WebMethod
    @ResponseWrapper(localName = "setupRobotResponse", targetNamespace = "http://ws.hub.setrobot.crystals.ru/", className = "project.lighthouse.autotests.robotClient.SetupRobotResponse")
    public String setupRobot(
            @WebParam(name = "cashIp", targetNamespace = "")
            String cashIp
    ) throws InterruptedException_Exception;
}
