package project.lighthouse.autotests.robotClient;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-09-09T11:39:32.075+04:00
 * Generated source version: 2.7.6
 */

public class SetRobotHubWSService extends Service {

    public final static URL WSDL_LOCATION;

    private final static String TARGET_NAMESPACE = System.getProperty("robot.target.namespace");
    private final static String URL_STRING = System.getProperty("robot.wsdl.url");

    public final static QName SERVICE = new QName(TARGET_NAMESPACE, "SetRobotHubWSService");
    public final static QName SetRobotHubWSPort = new QName(TARGET_NAMESPACE, "SetRobotHubWSPort");

    static {
        URL url = null;
        try {
            url = new URL(URL_STRING);
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SetRobotHubWSService.class.getName())
                    .log(java.util.logging.Level.INFO,
                            "Can not initialize the default wsdl from {0}", URL_STRING);
        }
        WSDL_LOCATION = url;
    }

    public SetRobotHubWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SetRobotHubWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SetRobotHubWSService() {
        super(WSDL_LOCATION, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SetRobotHubWSService(WebServiceFeature... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SetRobotHubWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SetRobotHubWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns SetRobotHubWS
     */
    @WebEndpoint(name = "SetRobotHubWSPort")
    public SetRobotHubWS getSetRobotHubWSPort() {
        return super.getPort(SetRobotHubWSPort, SetRobotHubWS.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns SetRobotHubWS
     */
    @WebEndpoint(name = "SetRobotHubWSPort")
    public SetRobotHubWS getSetRobotHubWSPort(WebServiceFeature... features) {
        return super.getPort(SetRobotHubWSPort, SetRobotHubWS.class, features);
    }
}
