load 'deploy' if respond_to?(:namespace)

require 'colored'
require 'capifony_symfony2'

# add local recipes to load path
$:.unshift(File.expand_path('../deploy/capistrano/plugins'))

load '../deploy/capistrano/recipes/deploy'
load '../deploy/capistrano/recipes/log'
load '../deploy/capistrano/recipes/webfront'
load 'config/deploy'