load 'deploy' if respond_to?(:namespace)

require 'colored'

# add local recipes to load path
$:.unshift(File.expand_path('../deploy/plugins'))

load '../deploy/recipes/deploy'
load '../deploy/recipes/log'
load '../deploy/recipes/webfront'
load 'deploy/deploy'