source "http://rubygems.org"

gem 'capistrano', :git => 'https://github.com/crystalservice/capistrano.git', :branch => 'fetch-pull-request'
gem "capistrano-ext"
gem "capistrano_colors"
gem "colored"
gem "time_diff"
